version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/zzz-project  # 프로젝트 이름
    overwrite: yes


permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root



### 새로 추가한 부분 ###
hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180
      runas: root
    - location: scripts/health_check.sh
      timeout: 180
      runas: root
    - location: scripts/switch.sh
      timeout: 180
      runas: root

